name: hello!

on:
  push:
    branches:
      - master

jobs:
  hello_job:
    runs-on: ubuntu-20.04
    steps:
      - name: say hello
        run: echo "Hello github"
      - name: Time now
        run: date
      - name: Directory contents
        run: ls -l
